# Generated by Django 4.2.7 on 2023-12-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_remove_user_following'),
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
